# Generated by Django 3.0.8 on 2020-07-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
