# Generated by Django 3.0.8 on 2020-07-09 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200709_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='otp_exp',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='phone_verified',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='zip',
        ),
    ]
