# Generated by Django 3.0.8 on 2020-07-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200709_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
