# Generated by Django 3.0.8 on 2020-07-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
