# Generated by Django 3.0.8 on 2020-07-19 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200719_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='social_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
