# Generated by Django 3.0.8 on 2020-07-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20200719_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='id_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
