# Generated by Django 3.0.8 on 2020-07-21 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_myuser_id_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
