# Generated by Django 3.0.8 on 2020-08-02 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20200721_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='lang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
