# Generated by Django 3.0.8 on 2020-07-28 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('no_bed_room', models.IntegerField(default=1)),
                ('no_bath_room', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=255)),
                ('approx_sqf', models.FloatField(default=0.0)),
                ('per_month_rent', models.IntegerField(default=0)),
                ('nego', models.BooleanField(default=False)),
                ('lat', models.FloatField(null=True)),
                ('long', models.FloatField(null=True)),
                ('prop_type', models.CharField(max_length=255, null=True)),
                ('add_features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('rule', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('prop_details', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=8)),
                ('more_detail', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
