# Generated by Django 3.0.8 on 2020-07-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
