# Generated by Django 3.0.8 on 2020-07-31 19:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_auto_20200728_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='add_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='prop_details',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None),
        ),
        migrations.AlterField(
            model_name='property',
            name='rule',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), size=None),
        ),
    ]
